<a href="https://colab.research.google.com/github/deepan98raj-dotcom/Assessment/blob/main/Pandas_data_manipulation_Assign_on_3_7_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # What is pandas ?

 Pandas is a Python library used to:
  * Work with Tabular data (like Excel)
  * Clean data
  * Analyze data easily

It makes data handling **fast,simple,and powerful.**

# Importing Pandas

In [ ]:
import pandas as pd

print('Pandas imported successfully')

Pandas imported successfully

# Pandas Data Stuctures

> **Series**
   * One-dimensional
   * Similar to a single column in Excel

> **DataFrame**

   * Two-Dimensional  
   * Rows and columns like an Excel table

In [ ]:
# Creating a pandas Series

numbers = pd.Series([10,20,30,40,50])
print(numbers)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
# Creating a Pandas Dataframe

student_data = {
    'Name' : ['asha','ravi','meena','karthick','sri'],
    'Age' :[20,21,19,22,21],
    'Marks' :[85,90,78,88,99]
}

df = pd.DataFrame(student_data)
print(df)

       Name  Age  Marks
0      asha   20     85
1      ravi   21     90
2     meena   19     78
3  karthick   22     88
4       sri   21     99

In [ ]:
df.head()

       Name  Age  Marks
0      asha   20     85
1      ravi   21     90
2     meena   19     78
3  karthick   22     88
4       sri   21     99

In [ ]:
df.tail()

       Name  Age  Marks
0      asha   20     85
1      ravi   21     90
2     meena   19     78
3  karthick   22     88
4       sri   21     99

In [ ]:
#Shape,size,columns & info
df.shape

(5, 3)

In [ ]:
df.size

15

In [ ]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [ ]:
# Pratice
data_info= {
    'Empname' : ['Deva','raj','ram','janani'],
    'Salary' :['20K','35K','25K','40K'],
    'Experience' : [5,8,6,12]
}

df1 = pd.DataFrame(data_info)
print(df1)

  Empname Salary  Experience
0    Deva    20K           5
1     raj    35K           8
2     ram    25K           6
3  janani    40K          12

# Real-World Data Sources

In Practice,data is not created manually.It usually comes from:

    * CSV files(most common)
    * Excel files
    * Databases / APIs(later)

 **CSV and Excel files.**

In [ ]:
import pandas as pd

df = pd.read_csv('/content/WineQT.csv')
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB

In [ ]:
df.shape

(1143, 13)

In [ ]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
Id                        int64
dtype: object

In [ ]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111,5.657043,804.969379
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196,0.805824,463.997116
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000,0.000000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000,5.000000,411.000000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000,6.000000,794.000000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000,6.000000,1209.500000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000,1597.000000

# Data Cleaning with Pandas

Outcome : students can clean messy real world data confidently

**Project workflow**:

1. Problem Denfinition
2. Data Collection
3. Data cleaning(70% of time)
4. Exploratory Data Analysis(EDA)
5. Feature Engineering
6. Model Building
7. Model Evaluation
8. Deployment & Monitoring

In [ ]:
import pandas as pd

df_ti = pd.read_csv('/content/Titanic-Dataset.csv')
df_ti.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.shape

(1143, 13)

In [ ]:
# Checking Missing Values

# isnull() - helps identift missing values.

df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [ ]:
# Handing Missing Values

# > dropna() - Remove rows with missing values

# Used when missing data is very small.

In [ ]:
# Example (not applied permanently)

df.dropna().shape

(1143, 13)

In [ ]:
# Fill missing values with column mean (example)

# df['Age'].fillna(df['Age'].mean(),inplace=True)

df_filled = df.fillna(df.mean(numeric_only=True))

df_filled.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [ ]:
# Removing Duplicate Records

df_no_dup = df.drop_duplicates()
df_no_dup.shape

(1143, 13)

In [ ]:
df_renamed = df.rename(columns={'Pclass':'Passenger Class'})
df_renamed.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4

In [ ]:
df_ti.sort_values(by='Age',ascending=False).head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q

In [ ]:
df_ti.sort_values(by=['Age','Fare'],ascending=[True,False]).head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S

In [ ]:
df['quality'].value_counts()

quality
5    483
6    462
7    143
4     33
8     16
3      6
Name: count, dtype: int64

In [ ]:
# Basic statistical Functions

df['alcohol'].mean()

np.float64(10.442111402741325)

In [ ]:
df['alcohol'].max()

14.9

In [ ]:
df.mean(numeric_only = True)

fixed acidity             8.311111
volatile acidity          0.531339
citric acid               0.268364
residual sugar            2.532152
chlorides                 0.086933
free sulfur dioxide      15.615486
total sulfur dioxide     45.914698
density                   0.996730
pH                        3.311015
sulphates                 0.657708
alcohol                  10.442111
quality                   5.657043
Id                      804.969379
dtype: float64

In [ ]:
df.sum(numeric_only=True)

fixed acidity             9499.600000
volatile acidity           607.320000
citric acid                306.740000
residual sugar            2894.250000
chlorides                   99.364000
free sulfur dioxide      17848.500000
total sulfur dioxide     52480.500000
density                   1139.262860
pH                        3784.490000
sulphates                  751.760000
alcohol                  11935.333333
quality                   6466.000000
Id                      920080.000000
dtype: float64

In [ ]:
df.groupby('quality')['alcohol'].mean()

quality
3     9.691667
4    10.260606
5     9.902277
6    10.655339
7    11.482634
8    11.937500
Name: alcohol, dtype: float64

In [ ]:
df.sort_values(by='alcohol',ascending=False).head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
462,15.9,0.36,0.65,7.5,0.096,22.0,71.0,0.99760,2.98,0.84,14.9,5,652
419,5.0,0.42,0.24,2.0,0.060,19.0,50.0,0.99170,3.72,0.74,14.0,8,588
589,4.9,0.42,0.00,2.1,0.048,16.0,42.0,0.99154,3.71,0.74,14.0,7,821
898,5.0,0.38,0.01,1.6,0.048,26.0,60.0,0.99084,3.70,0.75,14.0,6,1270
98,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.0,6,144
96,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.0,6,142
329,8.8,0.46,0.45,2.6,0.065,7.0,18.0,0.99470,3.32,0.79,14.0,6,467
1054,5.3,0.47,0.11,2.2,0.048,16.0,89.0,0.99182,3.54,0.88,13.6,7,1477
787,5.0,0.40,0.50,4.3,0.046,29.0,80.0,0.99020,3.49,0.66,13.6,6,1114
868,5.1,0.42,0.00,1.8,0.044,18.0,88.0,0.99157,3.68,0.73,13.6,7,1228

In [ ]:
import pandas as pd

# weblink = https://www.kaggle.com/datasets/shub99/student-marks

url = 'https://storage.googleapis.com/kagglesdsdata/datasets/1510731/2495246/marks.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20260801%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260801T210951Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=53721d727e5be8f22c3ec62fb0190176620723d54fb6811c91f78d7a61d48316c65c134e6fbf0e58f16280393894305456d0f0099090db154f3eaf288dac321f85a070e4d6c7944dd6c2d6ec6d26454ae1d281d49f7c245a5f699d7442b3e0da8e92d55955ec5eaadeaaad77191290e4cbc9f9dd2fcd9aa07b3ce33b5bbcb0a0fe9ee25ab0564150972753c2e09b0233fcbea7b50c0ae671a16151455b17458b00f9b29c207e64ebb46475093192e2097e8c9f626967a6ef21f6bc7cf6de55e971714a08f8ef0444564c083b95b0e48bda5b540f21a373fe77e01e8b1590f40870539b5b1a80f6aa7de2a88b3eaa3b653a09882be8545eafd7505fbdbf17e4fc'
df_marks = pd.read_csv(url)

# The DataFrame df_marks currently has 3 data columns (the student names are in the index).
# The 'column' list must match the number of data columns.
column = ['MID-SEM-MARKS ',' END-SEM-MARKS','RESULT']
df_marks.columns = column

NAME = ['Svaraj','Pravarsh','Harshil','Tavyaan','Udbhav','Reyansh','Vatsalya','Deepan','Chitraksh','Karthav','Shaurya',
       'Vedant','Taarush','Parth','Zivaan','Ivaansh','Nydhiv','Advait','Kriyansh','Lakshyansh','Vaarish','Samarth',
       'Vivaan','Hridhaan','Paarth','Nishkarsh','Viraj','Tranay','Yashil','Eklavya','Chanaksh','Kavyansh','Druvansh',
       'Veeresh','Tanmay','Shivansh','Neeraj','Arish','Virohan','Gyanesh','Satvir','Armaan','Taksh','Rishabh','Rayansh',
       'Nandan','Chiransh','Vedarth','Saatvic','Bhavyansh','Aanya','Kiara','Navya','Prishaa','Aarohi','Mithila','Triveni',
       'Rudrani','Saanvi','Idhika','Viveka','Siyona','Trisha','Ananya','Dhriti','Yashita','Prakriti','Vividha','Sharvani',
       'Nairiti','Kaveri','Tarini','Mishka','Avantika','Urvi','Charvi','Nysha','Geetanjali','Divisha','Krithika','Kimaya',
       'Aishani','Bhavini','Shreeja','Varnika','Taarini','Ishika','Suhana','Darshanaa','Svanika','Vedika','Nityasri','Avyukta']

# Ensure the DataFrame has the same number of rows as the 'NAME' list
df_marks = df_marks.head(len(NAME))

# Add the 'NAME' column without setting it as the index
df_marks['NAME'] = NAME

display(df_marks.head())

   MID-SEM-MARKS    END-SEM-MARKS  RESULT      NAME
0       30.286711       43.894998       0    Svaraj
1       35.847409       72.902198       0  Pravarsh
2       60.182599       86.308552       1   Harshil
3       79.032736       75.344376       1   Tavyaan
4       45.083277       56.316372       0    Udbhav

In [ ]:
df_marks['S.NO'] = range(1, len(df_marks) + 1)

import numpy as np

# Generate random ages between 25 and 27 for each row
df_marks['Age'] = np.random.randint(25, 28, size=len(df_marks))

display(df_marks.head())

   MID-SEM-MARKS    END-SEM-MARKS  RESULT      NAME  S.NO  Age
0       30.286711       43.894998       0    Svaraj     1   26
1       35.847409       72.902198       0  Pravarsh     2   26
2       60.182599       86.308552       1   Harshil     3   27
3       79.032736       75.344376       1   Tavyaan     4   26
4       45.083277       56.316372       0    Udbhav     5   26

In [ ]:
df_marks = df_marks[['S.NO', 'NAME','Age', 'MID-SEM-MARKS ', ' END-SEM-MARKS', 'RESULT']]

df_marks['Pass or Fail'] = np.where(df_marks['RESULT'] == 1, 'Pass', 'Fail')
display(df_marks.head(46))

    S.NO        NAME  Age  MID-SEM-MARKS    END-SEM-MARKS  RESULT Pass or Fail
0      1      Svaraj   26       30.286711       43.894998       0         Fail
1      2    Pravarsh   26       35.847409       72.902198       0         Fail
2      3     Harshil   27       60.182599       86.308552       1         Pass
3      4     Tavyaan   26       79.032736       75.344376       1         Pass
4      5      Udbhav   26       45.083277       56.316372       0         Fail
5      6     Reyansh   25       61.106665       96.511426       1         Pass
6      7    Vatsalya   25       75.024746       46.554014       1         Pass
7      8      Deepan   27       76.098787       87.420570       1         Pass
8      9   Chitraksh   25       84.432820       43.533393       1         Pass
9     10     Karthav   25       95.861555       38.225278       0         Fail
10    11     Shaurya   25       75.013658       30.603263       0         Fail
11    12      Vedant   26       82.307053       76.481963       1         Pass
12    13     Taarush   25       69.364589       97.718692       1         Pass
13    14       Parth   26       39.538339       76.036811       0         Fail
14    15      Zivaan   25       53.971052       89.207350       1         Pass
15    16     Ivaansh   27       69.070144       52.740470       1         Pass
16    17      Nydhiv   25       67.946855       46.678574       0         Fail
17    18      Advait   26       70.661510       92.927138       1         Pass
18    19    Kriyansh   26       76.978784       47.575964       1         Pass
19    20  Lakshyansh   25       67.372028       42.838438       0         Fail
20    21     Vaarish   27       89.676776       65.799366       1         Pass
21    22     Samarth   27       50.534788       48.855812       0         Fail
22    23      Vivaan   25       34.212061       44.209529       0         Fail
23    24    Hridhaan   27       77.924091       68.972360       1         Pass
24    25      Paarth   27       62.271014       69.954458       1         Pass
25    26   Nishkarsh   25       80.190181       44.821629       1         Pass
26    27       Viraj   27       93.114389       38.800670       0         Fail
27    28      Tranay   27       61.830206       50.256108       0         Fail
28    29      Yashil   27       38.785804       64.995681       0         Fail
29    30     Eklavya   26       61.379289       72.807887       1         Pass
30    31    Chanaksh   26       85.404519       57.051984       1         Pass
31    32    Kavyansh   27       52.107980       63.127624       0         Fail
32    33    Druvansh   26       52.045405       69.432860       1         Pass
33    34     Veeresh   27       40.236894       71.167748       0         Fail
34    35      Tanmay   27       54.635106       52.213886       0         Fail
35    36    Shivansh   27       33.915500       98.869436       0         Fail
36    37      Neeraj   26       64.176989       80.908061       1         Pass
37    38       Arish   27       74.789253       41.573415       0         Fail
38    39     Virohan   26       34.183640       75.237720       0         Fail
39    40     Gyanesh   27       83.902394       56.308046       1         Pass
40    41      Satvir   27       51.547720       46.856290       0         Fail
41    42      Armaan   25       94.443368       65.568922       1         Pass
42    43       Taksh   25       82.368754       40.618255       0         Fail
43    44     Rishabh   27       51.047752       45.822701       0         Fail
44    45     Rayansh   25       62.222676       52.060992       0         Fail
45    46      Nandan   27       77.193035       70.458200       1         Pass

In [ ]:
display(df_marks.tail(47))

    S.NO        NAME  Age  MID-SEM-MARKS    END-SEM-MARKS  RESULT Pass or Fail
46    47    Chiransh   25       97.771599       86.727822       1         Pass
47    48     Vedarth   25       62.073064       96.768824       1         Pass
48    49     Saatvic   27       91.564974       88.696293       1         Pass
49    50   Bhavyansh   25       79.944818       74.163119       1         Pass
50    51       Aanya   26       99.272527       60.999031       1         Pass
51    52       Kiara   25       90.546714       43.390602       1         Pass
52    53       Navya   26       34.524514       60.396342       0         Fail
53    54     Prishaa   26       50.286496       49.804539       0         Fail
54    55      Aarohi   26       49.586677       59.808951       0         Fail
55    56     Mithila   27       97.645634       68.861573       1         Pass
56    57     Triveni   26       32.577200       95.598548       0         Fail
57    58     Rudrani   26       74.248691       69.824571       1         Pass
58    59      Saanvi   27       71.796462       78.453562       1         Pass
59    60      Idhika   26       75.395611       85.759937       1         Pass
60    61      Viveka   25       35.286113       47.020514       0         Fail
61    62      Siyona   27       56.253817       39.261473       0         Fail
62    63      Trisha   26       30.058822       49.592974       0         Fail
63    64      Ananya   26       44.668262       66.450086       0         Fail
64    65      Dhriti   26       66.560894       41.092098       0         Fail
65    66     Yashita   27       40.457551       97.535185       1         Pass
66    67    Prakriti   26       49.072563       51.883212       0         Fail
67    68     Vividha   25       80.279574       92.116061       1         Pass
68    69    Sharvani   27       66.746719       60.991394       1         Pass
69    70     Nairiti   27       32.722833       43.307173       0         Fail
70    71      Kaveri   27       64.039320       78.031688       1         Pass
71    72      Tarini   25       72.346494       96.227593       1         Pass
72    73      Mishka   26       60.457886       73.094998       1         Pass
73    74    Avantika   27       58.840956       75.858448       1         Pass
74    75        Urvi   26       99.827858       72.369252       1         Pass
75    76      Charvi   26       47.264269       88.475865       1         Pass
76    77       Nysha   26       50.458160       75.809860       1         Pass
77    78  Geetanjali   27       60.455556       42.508409       0         Fail
78    79     Divisha   26       82.226662       42.719879       0         Fail
79    80    Krithika   25       88.913896       69.803789       1         Pass
80    81      Kimaya   25       94.834507       45.694307       1         Pass
81    82     Aishani   26       67.319257       66.589353       1         Pass
82    83     Bhavini   25       57.238706       59.514282       1         Pass
83    84     Shreeja   25       80.366756       90.960148       1         Pass
84    85     Varnika   26       68.468522       85.594307       1         Pass
85    86     Taarini   25       42.075455       78.844786       0         Fail
86    87      Ishika   27       75.477702       90.424539       1         Pass
87    88      Suhana   25       78.635424       96.647427       1         Pass
88    89   Darshanaa   26       52.348004       60.769505       0         Fail
89    90     Svanika   26       94.094331       77.159105       1         Pass
90    91      Vedika   26       90.448551       87.508792       1         Pass
91    92    Nityasri   27       55.482161       35.570703       0         Fail
92    93     Avyukta   27       74.492692       84.845137       1         Pass

In [ ]:
# columns selection

df_marks[['NAME','RESULT','Age']]

         NAME  RESULT  Age
0      Svaraj       0   26
1    Pravarsh       0   26
2     Harshil       1   27
3     Tavyaan       1   26
4      Udbhav       0   26
..        ...     ...  ...
88  Darshanaa       0   26
89    Svanika       1   26
90     Vedika       1   26
91   Nityasri       0   27
92    Avyukta       1   27

[93 rows x 3 columns]

In [ ]:
# Row Selection

df_marks[0:5]

   S.NO      NAME  Age  MID-SEM-MARKS    END-SEM-MARKS  RESULT Pass or Fail
0     1    Svaraj   26       30.286711       43.894998       0         Fail
1     2  Pravarsh   26       35.847409       72.902198       0         Fail
2     3   Harshil   27       60.182599       86.308552       1         Pass
3     4   Tavyaan   26       79.032736       75.344376       1         Pass
4     5    Udbhav   26       45.083277       56.316372       0         Fail

In [ ]:
df_marks[df_marks[' END-SEM-MARKS']> 85]

    S.NO      NAME  Age  MID-SEM-MARKS    END-SEM-MARKS  RESULT Pass or Fail
2      3   Harshil   27       60.182599       86.308552       1         Pass
5      6   Reyansh   25       61.106665       96.511426       1         Pass
7      8    Deepan   27       76.098787       87.420570       1         Pass
12    13   Taarush   25       69.364589       97.718692       1         Pass
14    15    Zivaan   25       53.971052       89.207350       1         Pass
17    18    Advait   26       70.661510       92.927138       1         Pass
35    36  Shivansh   27       33.915500       98.869436       0         Fail
46    47  Chiransh   25       97.771599       86.727822       1         Pass
47    48   Vedarth   25       62.073064       96.768824       1         Pass
48    49   Saatvic   27       91.564974       88.696293       1         Pass
56    57   Triveni   26       32.577200       95.598548       0         Fail
59    60    Idhika   26       75.395611       85.759937       1         Pass
65    66   Yashita   27       40.457551       97.535185       1         Pass
67    68   Vividha   25       80.279574       92.116061       1         Pass
71    72    Tarini   25       72.346494       96.227593       1         Pass
75    76    Charvi   26       47.264269       88.475865       1         Pass
83    84   Shreeja   25       80.366756       90.960148       1         Pass
84    85   Varnika   26       68.468522       85.594307       1         Pass
86    87    Ishika   27       75.477702       90.424539       1         Pass
87    88    Suhana   25       78.635424       96.647427       1         Pass
90    91    Vedika   26       90.448551       87.508792       1         Pass

In [ ]:
df_marks[df_marks['Age'] >=26]

    S.NO       NAME  Age  MID-SEM-MARKS    END-SEM-MARKS  RESULT Pass or Fail
0      1     Svaraj   26       30.286711       43.894998       0         Fail
1      2   Pravarsh   26       35.847409       72.902198       0         Fail
2      3    Harshil   27       60.182599       86.308552       1         Pass
3      4    Tavyaan   26       79.032736       75.344376       1         Pass
4      5     Udbhav   26       45.083277       56.316372       0         Fail
..   ...        ...  ...             ...             ...     ...          ...
88    89  Darshanaa   26       52.348004       60.769505       0         Fail
89    90    Svanika   26       94.094331       77.159105       1         Pass
90    91     Vedika   26       90.448551       87.508792       1         Pass
91    92   Nityasri   27       55.482161       35.570703       0         Fail
92    93    Avyukta   27       74.492692       84.845137       1         Pass

[66 rows x 7 columns]

In [ ]:
df_marks.loc[df_marks[' END-SEM-MARKS'] < 80, ['NAME',' END-SEM-MARKS']]

         NAME   END-SEM-MARKS
0      Svaraj       43.894998
1    Pravarsh       72.902198
3     Tavyaan       75.344376
4      Udbhav       56.316372
6    Vatsalya       46.554014
..        ...             ...
82    Bhavini       59.514282
85    Taarini       78.844786
88  Darshanaa       60.769505
89    Svanika       77.159105
91   Nityasri       35.570703

[70 rows x 2 columns]

In [ ]:
df_marks.iloc[1,2]

np.int64(26)

In [ ]:
#34

import pandas as pd
data = {
    'alcohol' : [8.5,9.2,10.1,11.0,9.8,10.5,11.2,8.9],
    'sugar'   : [6.2,4.8,3.5,2.1,5.0,3.0,1.8,6.5],
    'pH'      : [3.2,3.1,3.0,3.3,3.2,3.1,3.4,3.0],
    'quality' : [5,6,7,8,6,7,8,5],
    'price_category' :['Low','medium','high','high','medium','Low','medium','high']
}

df = pd.DataFrame(data)
df

   alcohol  sugar   pH  quality price_category
0      8.5    6.2  3.2        5            Low
1      9.2    4.8  3.1        6         medium
2     10.1    3.5  3.0        7           high
3     11.0    2.1  3.3        8           high
4      9.8    5.0  3.2        6         medium
5     10.5    3.0  3.1        7            Low
6     11.2    1.8  3.4        8         medium
7      8.9    6.5  3.0        5           high

In [ ]:
# 1. groupby() Basics
#   - Used to group data based on a column and perform calculations on each group.

# Average alcohol content by quality
df.groupby('quality')['alcohol'].mean()

quality
5     8.7
6     9.5
7    10.3
8    11.1
Name: alcohol, dtype: float64

In [ ]:
# 2.Single Aggregation

# Here we calculate mean sugur level for each price category.

df.groupby('price_category')['sugar'].mean()

price_category
Low       4.600000
high      4.033333
medium    3.866667
Name: sugar, dtype: float64

In [ ]:
# 3. Multiple Aggregations

# - We can calculate more than one statistic at once.

df.groupby('quality')['alcohol'].agg(['mean','max','min'])

         mean   max   min
quality
5         8.7   8.9   8.5
6         9.5   9.8   9.2
7        10.3  10.5  10.1
8        11.1  11.2  11.0

In [ ]:
# 4 Using agg() with Multiple Columns & Functions

df.groupby('price_category').agg({'alcohol': ['mean','max'],
                                  'sugar': 'mean',
                                  'quality': 'count'})

                  alcohol           sugar quality
                     mean   max      mean   count
price_category
Low              9.500000  10.5  4.600000       2
high            10.000000  11.0  4.033333       3
medium          10.066667  11.2  3.866667       3

In [ ]:
# reset_index()

grouped = df.groupby('quality')['alcohol'].mean().reset_index()
grouped

   quality  alcohol
0        5      8.7
1        6      9.5
2        7     10.3
3        8     11.1

In [ ]:
# 6. Multiple - Column GroupBy

df.groupby(['price_category','quality'])['alcohol'].mean().reset_index()

  price_category  quality  alcohol
0            Low        5      8.5
1            Low        7     10.5
2           high        5      8.9
3           high        7     10.1
4           high        8     11.0
5         medium        6      9.5
6         medium        8     11.2